name: app_idosos
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5


  lottie: ^2.6.0

  #firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7


  #imagepicker
  image_network: ^2.5.4+1
  image_picker: ^1.0.4
  #validator
  brasil_fields: ^1.9.0
  email_validator: ^2.1.17

  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.2.2

  #LocalDB
  objectbox: ^4.0.0
  objectbox_flutter_libs: any
  path_provider: ^2.1.1

  #alarms
  timezone: ^0.9.2
  periodic_alarm: ^0.0.41
  flutter_alarm_clock: ^0.1.1

  #notificação
  awesome_notifications: ^0.7.4+1
  overlay_support: ^2.1.0

  #Tela Hidydration
  liquid_progress_indicator_v2: ^0.5.0
  water_bottle: ^0.0.7

  #Agendador
  cron: ^0.5.1
  #Abrir URL
  url_launcher: ^6.2.5
  #Call telephone
  flutter_phone_direct_caller: ^2.1.1

  extended_masked_text: ^2.3.1
  #icons
  material_symbols_icons: ^4.2671.0
  #date picker
  calendar_date_picker2: ^1.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter



  mobx_codegen: ^2.4.0
  build_runner: ^2.3.3
  build_resolvers: ^2.3.2
  objectbox_generator: any





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/alarms/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
